# Generated by Django 2.1.5 on 2019-04-16 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='houses',
            name='create_datetime',
            field=models.DateTimeField(auto_now=True, verbose_name='发布时间'),
        ),
        migrations.AlterField(
            model_name='houses',
            name='audit_type',
            field=models.PositiveIntegerField(choices=[(1, '待审核'), (2, '审核失败'), (3, '审核通过')], verbose_name='审核状态'),
        ),
    ]
